### PR TITLE
Upgrade from SiteGenesis to SFRA

### PR DESCRIPTION
**Pull request by nappa85**
The `guard` object doesn't exists in SFRA, this does the same but using the `server` object.
I also added a `cartridges` parent folder, as standard.

### CODE REVIEW

**Comment by vsanse** [comment]
Hey @nappa85 ,

Thanks for your interest in the project and the PR. If you check the release section I'm already attaching both versions SGJC and SFRA.https://github.com/vsanse/plugin_sf_pwa/releases

**Comment by nappa85** [comment]
Oh, yeah, you're right, I was asking myself how do you create those two versions without a branch, and only now I noticed the .txt file...
I edited it to use the https middleware.

My problem is: I need to integrate this plugin in a CI build system, therefore the `cartridges` folder and the need to point to a version who defaults to SFRA without interactions.
Do you think it's acceptable to default to SFRA, or at least manage it in a separate branch instead of a txt file?

**Comment by vsanse** [comment]
Yeah. I guess we can do that. Could you modify your PR to suit better with SFRA and I'll create a separate branch or Repo for SGJC

Also, If you can help in an issue, the manifest JSON included in head via link tag gives `401` error when the site is in status `online(protected)` causing issues with PWA installability

**Comment by nappa85** [comment]
Ok, I've already modified two files to tell the browser to use the same auth of the main page, it should be enough and it doesn't interfere with the normal behaviour without basic auth.

Modified files are:
* cartridges/plugin_sf_pwa/cartridge/templates/default/pwa/register.isml
* cartridges/plugin_sf_pwa/cartridge/templates/default/pwa/sw.isml

I've made a not-so-extensive test and it worked.
Let me know if it's enough

**Comment by vsanse** [comment]
Checked! this is working well. You can use `git clone -b v3.0 --single-branch https://github.com/vsanse/plugin_sf_pwa.git` in your CI build system.

**Comment by nappa85** [comment]
Fantastic, works like a charm, thank you very much!

**Comment by vsanse** [comment]
Hey @nappa85,

I need to make this repo private due to some organization issues around certification. This repo will be available shortly with salesforce commerce cloud itself after a few modifications so hang on and thanks for helping out.

cheers!

**Pull request merged**
